version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    container_name: cockroachdb
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - ./cockroach-data:/cockroach/cockroach-data
    command: start-single-node --insecure

volumes:
  cockroach-data: